- name: Mysql Setup
  hosts: all
  become: yes
  tasks:
    - name: install mysql server
      ansible.builtin.dnf:
         name: mysql
         state: installed
    - name: enable mysql server
      ansible.builtin.systemd_service:
        name: mysql
        state: installed
        enabled: yes

    - name: setup root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1












  print_heading_task "install mysql "
  dnf install mysql-server -y &>>$log
  check_status $?

  print_heading_task "enable mysql service"
  systemctl enable mysqld &>>$log
  systemctl start mysqld &>>$log
  check_status $?

  print_heading_task "setup root password"
  echo 'show databases' | mysql -h mysql-dev.ganeshreddy12.online -uroot -p${mysql_root_password}  &>>$log
  if [ $? -ne 0 ]; then
  mysql_secure_installation --set-root-pass ${mysql_root_password} &>>$log
  fi
  check_status $?
