- name: MySql Setup
  hosts: all
  become: yes
  tasks:
    - name: install MySql server
      ansible.builtin.dnf:
         name: mysql
         state: installed
    - name: Enable MySql Server
      ansible.builtin.systemd_service:
         name: mysqld
         state: started
         enabled: yes
    - name: setup root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1













