- name: MySql Setup
  hosts: all
  become: yes
  tasks:
    - name: install MySql server
      ansible.builtin.dnf:
         name: mysql
         state: installed

    - name : MYSQL server
      ansible.builtin.systemd_service:
        state: restarted
        name: mysqld
        enabled: yes

    - name: setup MySQL password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1















