- name: Mysql Setup
  hosts: all
  become: yes
  tasks:
    - name: install mysql server
      ansible.builtin.dnf:
         name: mysql
         state: installed
    - name: Enable Mysql Server
      ansible.builtin.systemd_service:
         name: mysql
         state: started
         enabled: true
    - name: setup root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1













