format_version: 10
pipelines:
  mysql:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-309b167:
        git: https://github.com/ganeshkumardesai/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - dev:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                      - dev
                    command: bash
                    run_if: passed
      - QA:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                      - QA
                    command: bash
                    run_if: passed

      - stage:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                      - stage
                    command: bash
                    run_if: passed
      - prod:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                      - prod
                    command: bash
                    run_if: passed
